site_name: Physics Problems
site_url: https://dchorazkiewicz.github.io/Physics_Problems_Repo

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: pl
          name: Polski
          build: true
          nav:
            - Home: 'index.md'
            - Wprowadzenie: '00_Intro.md'
            - Mechanika 1:
              - '01_Mechanics_1.md'
              - Notatki Dodatkowe:
                - Notatka 01: '01_Mechanics_1_solution/extra_01.md'
                - Notatka 02: '01_Mechanics_1_solution/extra_02.md'
                - Notatka 03: '01_Mechanics_1_solution/extra_03.md'
            - Mechanika 2: '02_Mechanics_2.md'
            - Fale: '03_Waves.md'
            - Elektromagnetyzm 1: '04_Electromagnetism_1.md'
            - Elektromagnetyzm 2: '05_Electromagnetism_2.md'
            - Obwody 1: '06_Circuits_1.md'
            - Obwody 2: '07_Circuits_2.md'
            - Pomiary: '08_Measurements.md'
            - Kosmos: '09_Cosmos.md'
            - Astronomia i Astrofizyka: '10_Astronomy_and_Astrophysics.md'
            - Kosmologia i Względność: '11_Cosmology_and_Relativity.md'
            - Fizyka Współczesna 1: '12_Modern_Physics_1.md'
            - Fizyka Współczesna 2: '13_Modern_Physics_2.md'
            - Animacje:
              - 'Rzut Ukośny': 'anim/projectile_motion.html'
              - 'Wahadło': 'anim/pendulum.html'
              - 'Stożkowe': 'anim/conics.html'
              - 'Prawa Keplera': 'anim/kepler.html'
              - 'Wahadło Chaotyczne': 'anim/chaos_pendulum.html'
              - 'Całka Pracy': 'anim/work_integral.html'
              - 'Strumień': 'anim/flux.html'
              - 'Całkowanie Pola Elektrycznego': 'anim/electric_field_integration.html'
              - 'Fale - atomy': 'anim/wave_atoms.html'
        - locale: en
          name: English
          default: true
          build: true
          nav:
            - Home: 'index.md'
            - Introduction: '00_Intro.md'
            - 'Mechanics 1':
              - '01_Mechanics_1.md'
              - Extra Notes:
                - Extra 01: '01_Mechanics_1_solution/extra_01.md'
                - Extra 02: '01_Mechanics_1_solution/extra_02.md'
                - Extra 03: '01_Mechanics_1_solution/extra_03.md'
            - 'Mechanics 2': '02_Mechanics_2.md'
            - Waves: '03_Waves.md'
            - 'Electromagnetism 1': '04_Electromagnetism_1.md'
            - 'Electromagnetism 2': '05_Electromagnetism_2.md'
            - 'Circuits 1': '06_Circuits_1.md'
            - 'Circuits 2': '07_Circuits_2.md'
            - Measurements: '08_Measurements.md'
            - Cosmos: '09_Cosmos.md'
            - 'Astronomy and Astrophysics': '10_Astronomy_and_Astrophysics.md'
            - 'Cosmology and Relativity': '11_Cosmology_and_Relativity.md'
            - 'Modern Physics 1': '12_Modern_Physics_1.md'
            - 'Modern Physics 2': '13_Modern_Physics_2.md'
            - Animations:
              - 'Projectile Motion': 'anim/projectile_motion.html'
              - 'Pendulum': 'anim/pendulum.html'
              - 'Conics': 'anim/conics.html'
              - "Kepler's Laws": 'anim/kepler.html'
              - 'Chaotic Pendulum': 'anim/chaos_pendulum.html'
              - 'Work Integral': 'anim/work_integral.html'
              - 'Flux': 'anim/flux.html'
              - 'Electric Field Integration': 'anim/electric_field_integration.html'
              - 'Atom waves': 'anim/wave_atoms.html'
            - Extra:
              - Problem 1:
                - 'Formulation': 'extra/problem_1/problem_1_formulation.md'
                - 'Solution': 'extra/problem_1/problem_solution.md'
              - Problem 2:
                - 'Formulation': 'extra/problem_2/problem_2_formulation.md'
                - 'Solution': 'extra/problem_2/problem_solution.md'
              - Problem 3:
                - 'Formulation': 'extra/problem_3/problem_3_formulation.md'
                - 'Solution': 'extra/problem_3/problem_solution.md'
              - Problem 4:
                - 'Formulation': 'extra/problem_4/problem_4_formulation.md'
                - 'Solution': 'extra/problem_4/problem_solution.md'