site_name: Physics Problems
theme:
  name: material
  palette:
    # Switch for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Switch for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode